import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Marinali Rooms",
  description: "Generated by create next app",
};

import { client } from "@/sanity/lib/client";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch theme colors directly in the layout
  // We look for both published and draft versions of the settings
  const settings = await client.fetch(
    `*[_type == "settings"] | order(_updatedAt desc)[0]{ primaryColor, secondaryColor, backgroundColor, textColor }`,
    {},
    { next: { revalidate: 0 } }
  );

  console.log('--- ALL THEME SETTINGS ---', settings);

  const primaryColor = settings?.primaryColor || "#e11d48";
  const secondaryColor = settings?.secondaryColor || "#4f46e5";
  const backgroundColor = settings?.backgroundColor || "#F8F6F2";
  const textColor = settings?.textColor || "#ffffff";

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      style={{
        // @ts-ignore
        "--primary-color": primaryColor,
        "--secondary-color": secondaryColor,
        "--background": backgroundColor,
        "--text-color": textColor,

      }}
    >
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
